# Generated by Django 5.2.12 on 2026-03-16 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LSTMPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('HOLD', 'HOLD')], max_length=4)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], default='NSE', max_length=3)),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('ticker', 'exchange', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], default='NSE', max_length=3)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'ticker', 'exchange')},
            },
        ),
    ]
